import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts", "tests/**/*.test.cjs"],
    environment: "node",
    coverage: {
      provider: "v8",
      reporter: ["text", "html"],
      include: [
        "supabase/functions/_shared/**/*.ts",
        "scripts/validate-tier1.cjs",
        "scripts/wave2-bundle-schedules.cjs",
      ],
      exclude: [
        "supabase/functions/scheduled-run-dispatcher/index.ts", // Deno-only entry point
        "supabase/functions/minion-worker/index.ts",            // Deno-only entry point
        "supabase/functions/_shared/schedules.generated.ts",    // auto-generated by bundler
      ],
    },
  },
});
