import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.test.ts", "tests/**/*.test.cjs"],
    environment: "node",
    // Some tests (e.g. tests/cla/preflight-drift.test.ts) deliberately mutate
    // the live repo's knowledge/*.yaml files to exercise drift validators,
    // then restore. Other tests (e.g. tests/validate-tier1.test.ts) read the
    // same files. File-level parallelism would race. Serialize files; tests
    // within a file still run in declaration order.
    fileParallelism: false,
    coverage: {
      provider: "v8",
      reporter: ["text", "html"],
      include: [
        "supabase/functions/_shared/**/*.ts",
        "scripts/validate-tier1.cjs",
        "scripts/wave2-bundle-schedules.cjs",
      ],
      exclude: [
        "supabase/functions/scheduled-run-dispatcher/index.ts", // Deno-only entry point
        "supabase/functions/minion-worker/index.ts",            // Deno-only entry point
        "supabase/functions/_shared/schedules.generated.ts",    // auto-generated by bundler
      ],
    },
  },
});
