// AUTO-GENERATED by scripts/wave2-bundle-invariants.cjs from
// knowledge/cross-tier-invariants.yaml. Do not edit by hand.
// Re-run with: pnpm wave2:bundle-invariants
//
// Source version: 1.0.0
// Invariant count: 14
// By layer: L1=3 L2=7 L3=4
// Generated at: 2026-05-14T08:40:21.189Z

import type { Invariant } from "./invariants.ts";

export const ALL_INVARIANTS: Invariant[] = [
  {
    "id": "snapshot-header-matches-newest-migration",
    "description": "supabase/schema-snapshot.sql header must reference the newest migration file",
    "kind": "header_match",
    "layer": "L3",
    "status": "deferred",
    "source": {
      "tier": 1,
      "ref": "supabase/schema-snapshot.sql",
      "query": "header:last_migration"
    },
    "target": {
      "tier": 1,
      "ref": "supabase/migrations/",
      "query": "ls | sort -V | tail -1"
    },
    "severity": "critical",
    "hitl_tier": "B",
    "fix_strategy": "regen_bundle",
    "notes": "Deferred — no snapshot file in v1.0a/b/c. Activates when v1.0d adds\n`supabase db dump` pipeline (requires Docker or direct pg_dump).\n"
  },
  {
    "id": "manifest-tier2-tables-subset",
    "description": "Every table listed in manifest.tier2_operational.schemas.ops MUST be CREATE TABLE'd by some migration",
    "kind": "subset",
    "layer": "L2",
    "source": {
      "tier": 1,
      "ref": "knowledge/manifest.yaml",
      "query": "$.tier2_operational.schemas.ops.tables[*].name"
    },
    "target": {
      "tier": 1,
      "ref": "supabase/migrations/",
      "query": "regex:CREATE TABLE (?:IF NOT EXISTS )?ops\\.([a-z_]+)"
    },
    "severity": "critical",
    "hitl_tier": "C",
    "fix_strategy": "patch_yaml"
  },
  {
    "id": "manifest-tier2-metrics-tables-subset",
    "description": "Every table listed in manifest.tier2_operational.schemas.metrics MUST be CREATE TABLE'd by some migration",
    "kind": "subset",
    "layer": "L2",
    "source": {
      "tier": 1,
      "ref": "knowledge/manifest.yaml",
      "query": "$.tier2_operational.schemas.metrics.tables[*].name"
    },
    "target": {
      "tier": 1,
      "ref": "supabase/migrations/",
      "query": "regex:CREATE TABLE (?:IF NOT EXISTS )?metrics\\.([a-z_]+)"
    },
    "severity": "critical",
    "hitl_tier": "C",
    "fix_strategy": "patch_yaml"
  },
  {
    "id": "manifest-migration-file-refs-exist",
    "description": "Every migration_file: path in manifest.yaml must point to an existing file",
    "kind": "exists",
    "layer": "L1",
    "source": {
      "tier": 1,
      "ref": "knowledge/manifest.yaml",
      "query": "$..migration_file"
    },
    "target": {
      "tier": 1,
      "ref": ".",
      "query": "file:exists"
    },
    "severity": "critical",
    "hitl_tier": "B",
    "fix_strategy": "patch_yaml"
  },
  {
    "id": "manifest-extended-by-paths-exist",
    "description": "Every extended_by: path in manifest.yaml must point to an existing migration file",
    "kind": "exists",
    "layer": "L1",
    "source": {
      "tier": 1,
      "ref": "knowledge/manifest.yaml",
      "query": "$..extended_by"
    },
    "target": {
      "tier": 1,
      "ref": ".",
      "query": "file:exists"
    },
    "severity": "critical",
    "hitl_tier": "B",
    "fix_strategy": "patch_yaml"
  },
  {
    "id": "schedules-skills-registered",
    "description": "Every `skill:` referenced in schedules.yaml must be in minion-worker SKILL_REGISTRY",
    "kind": "subset",
    "layer": "L2",
    "source": {
      "tier": 1,
      "ref": "knowledge/schedules.yaml",
      "query": "$.schedules[*].skill"
    },
    "target": {
      "tier": 1,
      "ref": "supabase/functions/minion-worker/index.ts",
      "query": "regex:\"([a-z-]+)\":\\s*make[A-Z]"
    },
    "severity": "critical",
    "hitl_tier": "B",
    "fix_strategy": "open_pr"
  },
  {
    "id": "code-table-references-exist",
    "description": "Every `.from('<table>')` in supabase/functions/ must reference a table CREATE'd by some migration",
    "kind": "subset",
    "layer": "L2",
    "source": {
      "tier": 1,
      "ref": "supabase/functions/",
      "query": "regex:\\.from\\(['\"]([a-z_]+)['\"]\\)"
    },
    "target": {
      "tier": 1,
      "ref": "supabase/migrations/",
      "query": "regex:CREATE TABLE (?:IF NOT EXISTS )?(?:ops|metrics|public)\\.([a-z_]+)"
    },
    "severity": "critical",
    "hitl_tier": "B",
    "fix_strategy": "open_pr"
  },
  {
    "id": "roles-skills-exist",
    "description": "Every skill mentioned in governance/ROLES.md must exist under 05-ai-ops/skills/",
    "kind": "subset",
    "layer": "L2",
    "source": {
      "tier": 1,
      "ref": "governance/ROLES.md",
      "query": "regex:^\\s*-\\s+([a-z][a-z0-9-]+)\\s*$"
    },
    "target": {
      "tier": 1,
      "ref": "05-ai-ops/skills/",
      "query": "ls"
    },
    "severity": "warn",
    "hitl_tier": "B",
    "fix_strategy": "manual_only",
    "notes": "ROLES.md is prose-heavy; the regex query is best-effort. False positives\nacceptable in v1.0a; refine in v1.1 with marker comments.\n"
  },
  {
    "id": "hitl-tier-d-actions-have-hook-or-exemption",
    "description": "Every Tier D action in governance/HITL.md must have an enforcement hook in .claude/hooks/ OR be marked not_enforced",
    "kind": "implies",
    "layer": "L2",
    "source": {
      "tier": 1,
      "ref": "governance/HITL.md",
      "query": "section:Tier D"
    },
    "target": {
      "tier": 1,
      "ref": ".claude/hooks/",
      "query": "ls"
    },
    "severity": "warn",
    "hitl_tier": "C",
    "fix_strategy": "manual_only",
    "notes": "v1.0a uses heuristic mapping. v1.1 will introduce explicit\nhitl_action_id ↔ hook_file marker comments for exact coverage.\n"
  },
  {
    "id": "schedules-bundle-matches-yaml",
    "description": "schedules.generated.ts must match the current schedules.yaml (regenerate via wave2-bundle-schedules.cjs)",
    "kind": "equal",
    "layer": "L1",
    "source": {
      "tier": 1,
      "ref": "knowledge/schedules.yaml",
      "query": "$.schedules[*].id"
    },
    "target": {
      "tier": 1,
      "ref": "supabase/functions/_shared/schedules.generated.ts",
      "query": "regex:^\\s*\"([a-z][a-z0-9-]+)\":\\s*\\{"
    },
    "severity": "critical",
    "hitl_tier": "A",
    "fix_strategy": "regen_bundle"
  },
  {
    "id": "event-subscriptions-types-exist",
    "description": "Every event_type in event-subscriptions.yaml must appear in at least one emitter (migration COMMENT, skill, hook) OR be marked as external",
    "kind": "implies",
    "layer": "L2",
    "source": {
      "tier": 1,
      "ref": "knowledge/event-subscriptions.yaml",
      "query": "$..event_type"
    },
    "target": {
      "tier": 1,
      "ref": "supabase/migrations/, supabase/functions/, 05-ai-ops/skills/",
      "query": "regex:event_type[\"':\\s]+([a-z][a-z0-9._-]+)"
    },
    "severity": "warn",
    "hitl_tier": "B",
    "fix_strategy": "manual_only"
  },
  {
    "id": "schema-snapshot-exists",
    "description": "supabase/schema-snapshot.sql must exist",
    "kind": "exists",
    "layer": "L3",
    "status": "deferred",
    "source": {
      "tier": 1,
      "ref": "supabase/schema-snapshot.sql",
      "query": "file:exists"
    },
    "target": {
      "tier": 1,
      "ref": ".",
      "query": "file:exists"
    },
    "severity": "critical",
    "hitl_tier": "A",
    "fix_strategy": "regen_bundle",
    "notes": "Deferred — needs Docker or direct pg_dump. Activates with v1.0d.\n"
  },
  {
    "id": "live-db-tables-match-manifest",
    "description": "Every ops.* table in live DB must appear in manifest.tier2_operational.schemas.ops.tables",
    "kind": "subset",
    "layer": "L3",
    "status": "live",
    "source": {
      "tier": 2,
      "ref": "ops.*",
      "query": "rpc:ops.get_ops_tables"
    },
    "target": {
      "tier": 1,
      "ref": "knowledge/manifest.yaml",
      "query": "$.tier2_operational.schemas.ops.tables[*].name"
    },
    "severity": "critical",
    "hitl_tier": "C",
    "fix_strategy": "patch_yaml",
    "notes": "Mirror of L2 manifest-tier2-tables-subset but uses LIVE DB (not migrations\non disk). Catches drift introduced via Supabase UI direct edits.\n"
  },
  {
    "id": "live-db-tables-have-rls",
    "description": "Every ops.* table in live DB should have RLS enabled",
    "kind": "implies",
    "layer": "L3",
    "status": "live",
    "source": {
      "tier": 2,
      "ref": "ops.*",
      "query": "rpc:ops.get_ops_rls_state"
    },
    "target": {
      "tier": 2,
      "ref": "ops.*",
      "query": "rpc:ops.get_ops_rls_state[rls_enabled=true]"
    },
    "severity": "warn",
    "hitl_tier": "B",
    "fix_strategy": "add_migration",
    "notes": "Catches the failure pattern seen with capability_runs and\ncapability_phase_events — added in migration 00011, RLS forgotten until\n00020 caught it manually. With this invariant active, any future RLS\ngap would be reported within 24h.\n"
  }
] as unknown as Invariant[];

function isLive(i: Invariant): boolean {
  return (i.status ?? "live") === "live";
}

export const L1_INVARIANTS_LIVE: Invariant[] = ALL_INVARIANTS.filter((i) => i.layer === "L1" && isLive(i));
export const L2_INVARIANTS_LIVE: Invariant[] = ALL_INVARIANTS.filter((i) => i.layer === "L2" && isLive(i));
export const L3_INVARIANTS_LIVE: Invariant[] = ALL_INVARIANTS.filter((i) => i.layer === "L3" && isLive(i));
