// AUTO-GENERATED by scripts/wave2-bundle-invariants.cjs from
// knowledge/cross-tier-invariants.yaml. Do not edit by hand.
// Re-run with: pnpm wave2:bundle-invariants
//
// Source version: 1.0.0
// Invariant count: 22
// By layer: L1=6 L2=10 L3=6
// Generated at: 2026-05-24T18:33:02.265Z

import type { Invariant } from "./invariants.ts";

export const ALL_INVARIANTS: Invariant[] = [
  {
    "id": "snapshot-header-matches-newest-migration",
    "description": "supabase/schema-snapshot.sql header must reference the newest migration file",
    "kind": "header_match",
    "layer": "L3",
    "status": "deferred",
    "source": {
      "tier": 1,
      "ref": "supabase/schema-snapshot.sql",
      "query": "header:last_migration"
    },
    "target": {
      "tier": 1,
      "ref": "supabase/migrations/",
      "query": "ls | sort -V | tail -1"
    },
    "severity": "critical",
    "hitl_tier": "B",
    "fix_strategy": "regen_bundle",
    "notes": "Deferred — no snapshot file in v1.0a/b/c. Activates when v1.0d adds\n`supabase db dump` pipeline (requires Docker or direct pg_dump).\n"
  },
  {
    "id": "manifest-tier2-tables-subset",
    "description": "Every table listed in manifest.tier2_operational.schemas.ops MUST be CREATE TABLE'd by some migration",
    "kind": "subset",
    "layer": "L2",
    "source": {
      "tier": 1,
      "ref": "knowledge/manifest.yaml",
      "query": "$.tier2_operational.schemas.ops.tables[*].name"
    },
    "target": {
      "tier": 1,
      "ref": "supabase/migrations/",
      "query": "regex:CREATE TABLE (?:IF NOT EXISTS )?ops\\.([a-z_]+)"
    },
    "severity": "critical",
    "hitl_tier": "C",
    "fix_strategy": "patch_yaml"
  },
  {
    "id": "manifest-tier2-metrics-tables-subset",
    "description": "Every table listed in manifest.tier2_operational.schemas.metrics MUST be CREATE TABLE'd by some migration",
    "kind": "subset",
    "layer": "L2",
    "source": {
      "tier": 1,
      "ref": "knowledge/manifest.yaml",
      "query": "$.tier2_operational.schemas.metrics.tables[*].name"
    },
    "target": {
      "tier": 1,
      "ref": "supabase/migrations/",
      "query": "regex:CREATE TABLE (?:IF NOT EXISTS )?metrics\\.([a-z_]+)"
    },
    "severity": "critical",
    "hitl_tier": "C",
    "fix_strategy": "patch_yaml"
  },
  {
    "id": "manifest-migration-file-refs-exist",
    "description": "Every migration_file: path in manifest.yaml must point to an existing file",
    "kind": "exists",
    "layer": "L1",
    "source": {
      "tier": 1,
      "ref": "knowledge/manifest.yaml",
      "query": "$..migration_file"
    },
    "target": {
      "tier": 1,
      "ref": ".",
      "query": "file:exists"
    },
    "severity": "critical",
    "hitl_tier": "B",
    "fix_strategy": "patch_yaml"
  },
  {
    "id": "manifest-extended-by-paths-exist",
    "description": "Every extended_by: path in manifest.yaml must point to an existing migration file",
    "kind": "exists",
    "layer": "L1",
    "source": {
      "tier": 1,
      "ref": "knowledge/manifest.yaml",
      "query": "$..extended_by"
    },
    "target": {
      "tier": 1,
      "ref": ".",
      "query": "file:exists"
    },
    "severity": "critical",
    "hitl_tier": "B",
    "fix_strategy": "patch_yaml"
  },
  {
    "id": "schedules-skills-registered",
    "description": "Every `skill:` referenced in schedules.yaml must be in minion-worker SKILL_REGISTRY",
    "kind": "subset",
    "layer": "L2",
    "source": {
      "tier": 1,
      "ref": "knowledge/schedules.yaml",
      "query": "$.schedules[*].skill"
    },
    "target": {
      "tier": 1,
      "ref": "supabase/functions/minion-worker/index.ts",
      "query": "regex:\"([a-z-]+)\":\\s*make[A-Z]"
    },
    "severity": "critical",
    "hitl_tier": "B",
    "fix_strategy": "open_pr"
  },
  {
    "id": "code-table-references-exist",
    "description": "Every `.from('<table>')` in supabase/functions/ must reference a table CREATE'd by some migration",
    "kind": "subset",
    "layer": "L2",
    "source": {
      "tier": 1,
      "ref": "supabase/functions/",
      "query": "regex:\\.from\\(['\"]([a-z_]+)['\"]\\)"
    },
    "target": {
      "tier": 1,
      "ref": "supabase/migrations/",
      "query": "regex:CREATE TABLE (?:IF NOT EXISTS )?(?:ops|metrics|public)\\.([a-z_]+)"
    },
    "severity": "critical",
    "hitl_tier": "B",
    "fix_strategy": "open_pr"
  },
  {
    "id": "roles-skills-exist",
    "description": "Every skill mentioned in governance/ROLES.md must exist under 05-ai-ops/skills/",
    "kind": "subset",
    "layer": "L2",
    "source": {
      "tier": 1,
      "ref": "governance/ROLES.md",
      "query": "regex:^\\s*-\\s+([a-z][a-z0-9-]+)\\s*$"
    },
    "target": {
      "tier": 1,
      "ref": "05-ai-ops/skills/",
      "query": "ls"
    },
    "severity": "warn",
    "hitl_tier": "B",
    "fix_strategy": "manual_only",
    "notes": "ROLES.md is prose-heavy; the regex query is best-effort. False positives\nacceptable in v1.0a; refine in v1.1 with marker comments.\n"
  },
  {
    "id": "hitl-tier-d-actions-have-hook-or-exemption",
    "description": "Every Tier D action in governance/HITL.md must have an enforcement hook in .claude/hooks/ OR be marked not_enforced",
    "kind": "implies",
    "layer": "L2",
    "source": {
      "tier": 1,
      "ref": "governance/HITL.md",
      "query": "section:Tier D"
    },
    "target": {
      "tier": 1,
      "ref": ".claude/hooks/",
      "query": "ls"
    },
    "severity": "warn",
    "hitl_tier": "C",
    "fix_strategy": "manual_only",
    "notes": "v1.0a uses heuristic mapping. v1.1 will introduce explicit\nhitl_action_id ↔ hook_file marker comments for exact coverage.\n"
  },
  {
    "id": "schedules-bundle-matches-yaml",
    "description": "schedules.generated.ts must match the current schedules.yaml (regenerate via wave2-bundle-schedules.cjs)",
    "kind": "equal",
    "layer": "L1",
    "source": {
      "tier": 1,
      "ref": "knowledge/schedules.yaml",
      "query": "$.schedules[*].id"
    },
    "target": {
      "tier": 1,
      "ref": "supabase/functions/_shared/schedules.generated.ts",
      "query": "regex:^\\s*\"([a-z][a-z0-9-]+)\":\\s*\\{"
    },
    "severity": "critical",
    "hitl_tier": "A",
    "fix_strategy": "regen_bundle"
  },
  {
    "id": "event-subscriptions-types-exist",
    "description": "Every event_type in event-subscriptions.yaml must appear in at least one emitter (migration COMMENT, skill, hook) OR be marked as external",
    "kind": "implies",
    "layer": "L2",
    "source": {
      "tier": 1,
      "ref": "knowledge/event-subscriptions.yaml",
      "query": "$..event_type"
    },
    "target": {
      "tier": 1,
      "ref": "supabase/migrations/, supabase/functions/, 05-ai-ops/skills/",
      "query": "regex:event_type[\"':\\s]+([a-z][a-z0-9._-]+)"
    },
    "severity": "warn",
    "hitl_tier": "B",
    "fix_strategy": "manual_only"
  },
  {
    "id": "schema-snapshot-exists",
    "description": "supabase/schema-snapshot.sql must exist",
    "kind": "exists",
    "layer": "L3",
    "status": "deferred",
    "source": {
      "tier": 1,
      "ref": "supabase/schema-snapshot.sql",
      "query": "file:exists"
    },
    "target": {
      "tier": 1,
      "ref": ".",
      "query": "file:exists"
    },
    "severity": "critical",
    "hitl_tier": "A",
    "fix_strategy": "regen_bundle",
    "notes": "Deferred — needs Docker or direct pg_dump. Activates with v1.0d.\n"
  },
  {
    "id": "live-db-tables-match-manifest",
    "description": "Every ops.* table in live DB must appear in manifest.tier2_operational.schemas.ops.tables",
    "kind": "subset",
    "layer": "L3",
    "status": "live",
    "source": {
      "tier": 2,
      "ref": "ops.*",
      "query": "rpc:ops.get_ops_tables"
    },
    "target": {
      "tier": 1,
      "ref": "knowledge/manifest.yaml",
      "query": "$.tier2_operational.schemas.ops.tables[*].name"
    },
    "severity": "critical",
    "hitl_tier": "C",
    "fix_strategy": "patch_yaml",
    "notes": "Mirror of L2 manifest-tier2-tables-subset but uses LIVE DB (not migrations\non disk). Catches drift introduced via Supabase UI direct edits.\n"
  },
  {
    "id": "live-db-tables-have-rls",
    "description": "Every ops.* table in live DB should have RLS enabled",
    "kind": "implies",
    "layer": "L3",
    "status": "live",
    "source": {
      "tier": 2,
      "ref": "ops.*",
      "query": "rpc:ops.get_ops_rls_state"
    },
    "target": {
      "tier": 2,
      "ref": "ops.*",
      "query": "rpc:ops.get_ops_rls_state[rls_enabled=true]"
    },
    "severity": "warn",
    "hitl_tier": "B",
    "fix_strategy": "add_migration",
    "notes": "Catches the failure pattern seen with capability_runs and\ncapability_phase_events — added in migration 00011, RLS forgotten until\n00020 caught it manually. With this invariant active, any future RLS\ngap would be reported within 24h.\n"
  },
  {
    "id": "docs-page-has-source",
    "description": "Every MDX page in docs/content/ with source_path frontmatter must have a matching live source file in the codebase. Surfaces orphan pages.",
    "kind": "exists",
    "layer": "L1",
    "status": "deferred",
    "source": {
      "tier": 1,
      "ref": "docs/content/",
      "query": "frontmatter:source_path for *.mdx"
    },
    "target": {
      "tier": 1,
      "ref": "<source_path values>",
      "query": "fs:exists"
    },
    "severity": "critical",
    "hitl_tier": "B",
    "fix_strategy": "open_pr",
    "notes": "docs-engine v1.0 capability. Activates when Sprint 1 PR-3 lands the\nwalker + scripts/validate-docs-coverage.cjs. Auto-fix: /docs sync\nregenerates MDX from source; if source deleted, /docs sync removes\norphan MDX. Reports into docs_drift_count KPI.\n"
  },
  {
    "id": "docs-source-has-page",
    "description": "Every operating skill/agent/hook/command/SOP must have an MDX page in docs/content/. Surfaces missing pages.",
    "kind": "subset",
    "layer": "L2",
    "status": "deferred",
    "source": {
      "tier": 1,
      "ref": "<docs-engine walker scope>",
      "query": "fs:walk + matches walker scope"
    },
    "target": {
      "tier": 1,
      "ref": "docs/content/",
      "query": "rg '^source_path:' for each source file"
    },
    "severity": "warn",
    "hitl_tier": "A",
    "fix_strategy": "open_pr",
    "notes": "docs-engine v1.0 capability. Activates with Sprint 1. Reports into\ndocs_drift_count KPI. Currently deferred until the walker validator\nlands; once active, this invariant is the source of truth for\nwhether docs are in sync with the codebase. Auto-fix flow: /docs sync\ngenerates the missing MDX and opens a PR (per `open_pr` strategy).\n"
  },
  {
    "id": "gbrain-l1-page-embeddings-fresh",
    "description": "Every gbrain page has an up-to-date embedding (re-embed when page content sha differs from embedded sha)",
    "kind": "equal",
    "layer": "L1",
    "status": "deferred",
    "source": {
      "tier": 4,
      "ref": "gbrain DB pages.content_sha",
      "query": "SELECT page_id, content_sha FROM pages"
    },
    "target": {
      "tier": 4,
      "ref": "gbrain DB embeddings.embedded_sha",
      "query": "SELECT page_id, embedded_sha FROM embeddings"
    },
    "severity": "warn",
    "hitl_tier": "B",
    "fix_strategy": "regen_bundle",
    "notes": "gbrain-operational-brain v1.0. Activates Sprint 6 when validator handler\nlands in scripts/cross-tier/. Auto-fix: gbrain-maintainer dream cycle\nre-embeds stale pages nightly.\n"
  },
  {
    "id": "gbrain-l2-cross-link-integrity",
    "description": "Every ops.capability_runs.gbrain_proposal_slug exists as a gbrain page. Same for capability_phase_events and decisions.",
    "kind": "subset",
    "layer": "L2",
    "status": "deferred",
    "source": {
      "tier": 2,
      "ref": "ops.capability_runs.gbrain_proposal_slug + capability_phase_events.gbrain_meeting_slug + decisions.gbrain_concept_slug",
      "query": "SELECT gbrain_proposal_slug FROM ops.capability_runs WHERE gbrain_proposal_slug IS NOT NULL"
    },
    "target": {
      "tier": 4,
      "ref": "gbrain DB pages.slug",
      "query": "SELECT slug FROM pages"
    },
    "severity": "warn",
    "hitl_tier": "B",
    "fix_strategy": "open_pr",
    "notes": "gbrain-operational-brain v1.0 Sprint 3 migration adds the 3 cross-link\ncolumns. This invariant activates Sprint 6. Surfaces when a CLA run is\ndeleted but its gbrain narrative pages remain, or vice versa.\n"
  },
  {
    "id": "gbrain-l3-promotion-staleness",
    "description": "Brain pages with state=mature for >30 days imply ritsu.gbrain.promotion_pending event fires for weekly review",
    "kind": "implies",
    "layer": "L3",
    "status": "deferred",
    "source": {
      "tier": 4,
      "ref": "gbrain DB pages.state",
      "query": "SELECT slug FROM pages WHERE state = 'mature' AND state_since < now() - interval '30 days'"
    },
    "target": {
      "tier": 2,
      "ref": "ops.events",
      "query": "SELECT * FROM ops.events WHERE event_type = 'ritsu.gbrain.promotion_pending' AND payload->>'slug' = $1 AND created_at > now() - interval '7 days'"
    },
    "severity": "info",
    "hitl_tier": "A",
    "fix_strategy": "manual_only",
    "notes": "gbrain-operational-brain v1.0 Sprint 4 emits ritsu.gbrain.promotion_pending\nevent from the nightly cron. This invariant ensures the event keeps firing\nuntil founder acts (weekly promotion review per SOP-AIOPS-GBRAIN-002).\n"
  },
  {
    "id": "gbrain-l1-mcp-json-consistency",
    "description": ".mcp.json gbrain entry exists when knowledge/mcp-tools.yaml lists gbrain server tools",
    "kind": "exists",
    "layer": "L1",
    "status": "deferred",
    "source": {
      "tier": 1,
      "ref": "knowledge/mcp-tools.yaml",
      "query": "$.mcp_tools[?(@.server == 'gbrain')]"
    },
    "target": {
      "tier": 1,
      "ref": ".mcp.json",
      "query": "$.mcpServers.gbrain"
    },
    "severity": "critical",
    "hitl_tier": "C",
    "fix_strategy": "patch_yaml",
    "notes": "gbrain-operational-brain v1.0 Sprint 5 lands .mcp.json gbrain entry.\nThis invariant catches future drift between the entry and the tool\ncatalog. Companion to NEW L2 validator\nscripts/cross-tier/validate-mcp-json-tools-consistency.cjs (Sprint 6).\n"
  },
  {
    "id": "gbrain-l2-role-allowlist-consistency",
    "description": "governance/ROLES.md mcp_servers grants for gbrain MUST be subset of knowledge/mcp-roles.yaml entries",
    "kind": "subset",
    "layer": "L2",
    "status": "deferred",
    "source": {
      "tier": 1,
      "ref": "governance/ROLES.md",
      "query": "extract role blocks with mcp_servers containing 'gbrain'"
    },
    "target": {
      "tier": 1,
      "ref": "knowledge/mcp-roles.yaml",
      "query": "$.roles[*].id"
    },
    "severity": "critical",
    "hitl_tier": "C",
    "fix_strategy": "patch_yaml",
    "notes": "gbrain-operational-brain v1.0 Sprint 1 establishes the grants. This\ninvariant ensures ROLES.md grants don't drift past mcp-roles.yaml. Same\npattern as existing L2 'workforce personas ↔ ROLES.md ↔ runtime' validator.\n"
  },
  {
    "id": "gbrain-l3-pii-email-placeholder-confirmed-7d",
    "description": "Companies pages with EMAIL_PLACEHOLDER must imply pii_placeholder_replaced event within 7 days",
    "kind": "implies",
    "layer": "L3",
    "status": "deferred",
    "source": {
      "tier": 4,
      "ref": "gbrain DB pages",
      "query": "SELECT slug FROM pages WHERE page_type = 'company' AND content LIKE '%<<EMAIL_PLACEHOLDER>>%' AND state = 'draft' AND created_at < now() - interval '7 days'"
    },
    "target": {
      "tier": 2,
      "ref": "ops.events",
      "query": "SELECT * FROM ops.events WHERE event_type = 'ritsu.gbrain.write_committed' AND payload->>'slug' = $1 AND payload->>'pii_placeholder_replaced' = 'true'"
    },
    "severity": "warn",
    "hitl_tier": "B",
    "fix_strategy": "manual_only",
    "notes": "gbrain-operational-brain v1.0 Sprint 4 ships post-stripe-customer-created\nhook with PII placeholder pattern. This invariant catches placeholder pages\nsitting unconfirmed >7d (founder forgot to fill in email after Tier B\nnotify). Auto-fix: re-notify customer-lead role.\n"
  }
] as unknown as Invariant[];

function isLive(i: Invariant): boolean {
  return (i.status ?? "live") === "live";
}

export const L1_INVARIANTS_LIVE: Invariant[] = ALL_INVARIANTS.filter((i) => i.layer === "L1" && isLive(i));
export const L2_INVARIANTS_LIVE: Invariant[] = ALL_INVARIANTS.filter((i) => i.layer === "L2" && isLive(i));
export const L3_INVARIANTS_LIVE: Invariant[] = ALL_INVARIANTS.filter((i) => i.layer === "L3" && isLive(i));
