// AUTO-GENERATED by scripts/wave2-bundle-manifest-tables.cjs from
// knowledge/manifest.yaml. Do not edit by hand.
// Re-run with: pnpm wave2:bundle-manifest-tables
//
// Source version: 0.13.0
// ops tables:     33
// metrics tables: 1
// Generated at:   2026-05-26T14:28:23.436Z

export const MANIFEST_OPS_TABLES: readonly string[] = Object.freeze(
[
  "agent_runs",
  "alerts",
  "attention_log",
  "audit_log",
  "budget_alerts",
  "campaigns",
  "capability_phase_events",
  "capability_runs",
  "consistency_checks",
  "corrections",
  "cost_attributions",
  "decisions",
  "entity_edit_locks",
  "events",
  "evolve_extractions",
  "hitl_runs",
  "ingestion_jobs",
  "knowledge_embeddings",
  "knowledge_extractions",
  "knowledge_links",
  "knowledge_pages",
  "kpi_snapshots",
  "mcp_calls",
  "minion_jobs",
  "optimization_recommendations",
  "resolver_decisions",
  "run_summaries",
  "scheduled_runs",
  "settings",
  "sop_runs",
  "task_state_transitions",
  "tasks",
  "tier3_index"
]
);

export const MANIFEST_METRICS_TABLES: readonly string[] = Object.freeze(
[
  "product_dau_snapshot"
]
);
