// AUTO-GENERATED by scripts/wave2-bundle-schedules.cjs from knowledge/schedules.yaml.
// Do not edit by hand. Re-run with: pnpm wave2:bundle-schedules
//
// Source version:  1.0.0
// Source timezone: Asia/Ho_Chi_Minh
// Schedule count:  6
// Generated at:    2026-05-14T04:56:14.376Z

import type { ScheduleEntry } from "./dispatcher.ts";

export const SCHEDULES: Record<string, ScheduleEntry> = {
  "morning-brief-assembly": {
    "id": "morning-brief-assembly",
    "cron": "45 5 * * *",
    "description": "Assemble morning brief 15 min before founder block",
    "skill": "synthesize-morning-brief",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ],
    "requires_api": "anthropic",
    "fallback": "queue_for_founder_review",
    "cost_estimate": "$0.03 per run"
  },
  "etl-product-dau-hourly": {
    "id": "etl-product-dau-hourly",
    "cron": "5 * * * *",
    "description": "Hourly ETL of Product DAU snapshot to metrics.product_dau_snapshot",
    "skill": "etl-product-dau-snapshot",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ],
    "requires_api": "supabase_product_read",
    "fallback": "queue_for_founder_review",
    "cost_estimate": "$0.00 per run"
  },
  "stale-decision-check": {
    "id": "stale-decision-check",
    "cron": "0 9 * * MON",
    "description": "Identify decisions needing review (Bài #15)",
    "skill": "stale-decision-detector",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ]
  },
  "data-retention-scan": {
    "id": "data-retention-scan",
    "cron": "0 3 * * *",
    "description": "GDPR data retention enforcement (Bài #16)",
    "skill": "data-retention-scanner"
  },
  "ingestion-source-poll": {
    "id": "ingestion-source-poll",
    "cron": "*/30 * * * *",
    "description": "Poll active ingestion sources (Bài #18)",
    "skill": "ingestion-source-poller",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ]
  },
  "minion-queue-cleanup": {
    "id": "minion-queue-cleanup",
    "cron": "0 4 * * *",
    "description": "Cleanup completed Minion jobs > 30 days (Bài #5)",
    "skill": "minion-queue-cleaner"
  }
};

export const SCHEDULE_IDS: readonly string[] = ["data-retention-scan","etl-product-dau-hourly","ingestion-source-poll","minion-queue-cleanup","morning-brief-assembly","stale-decision-check"] as const;
