// AUTO-GENERATED by scripts/wave2-bundle-schedules.cjs from knowledge/schedules.yaml.
// Do not edit by hand. Re-run with: pnpm wave2:bundle-schedules
//
// Source version:  1.0.0
// Source timezone: Asia/Ho_Chi_Minh
// Schedule count:  9
// Generated at:    2026-05-18T05:18:05.478Z

import type { ScheduleEntry } from "./dispatcher.ts";

export const SCHEDULES: Record<string, ScheduleEntry> = {
  "morning-brief-assembly": {
    "id": "morning-brief-assembly",
    "cron": "45 5 * * *",
    "description": "Assemble morning brief 15 min before founder block",
    "skill": "synthesize-morning-brief",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ],
    "requires_api": "anthropic",
    "fallback": "queue_for_founder_review",
    "cost_estimate": "$0.03 per run"
  },
  "etl-product-dau-hourly": {
    "id": "etl-product-dau-hourly",
    "cron": "5 * * * *",
    "description": "Hourly ETL of Product DAU snapshot to metrics.product_dau_snapshot",
    "skill": "etl-product-dau-snapshot",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ],
    "requires_api": "supabase_product_read",
    "fallback": "queue_for_founder_review",
    "cost_estimate": "$0.00 per run"
  },
  "consistency-sweep-nightly": {
    "id": "consistency-sweep-nightly",
    "cron": "0 3 * * *",
    "description": "Nightly L3 sweep: insert pending consistency_checks rows for each L3 invariant",
    "skill": "consistency-sweep",
    "cost_estimate": "$0.00 per run"
  },
  "stale-decision-check": {
    "id": "stale-decision-check",
    "cron": "0 9 * * MON",
    "description": "Identify decisions needing review (Bài #15)",
    "skill": "stale-decision-detector",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ]
  },
  "data-retention-scan": {
    "id": "data-retention-scan",
    "cron": "0 3 * * *",
    "description": "GDPR data retention enforcement (Bài #16)",
    "skill": "data-retention-scanner"
  },
  "ingestion-source-poll": {
    "id": "ingestion-source-poll",
    "cron": "*/30 * * * *",
    "description": "Poll active ingestion sources (Bài #18)",
    "skill": "ingestion-source-poller",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ]
  },
  "minion-queue-cleanup": {
    "id": "minion-queue-cleanup",
    "cron": "0 4 * * *",
    "description": "Cleanup completed Minion jobs > 30 days (Bài #5)",
    "skill": "minion-queue-cleaner"
  },
  "wiki-embeddings-backfill": {
    "id": "wiki-embeddings-backfill",
    "cron": "0 * * * *",
    "description": "Backfill soft-deferred wiki embeddings (v2.0 G3 + v3.0 derived entities)",
    "skill": "wiki-embeddings-backfill",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ],
    "requires_api": "openai",
    "fallback": "skip_if_no_key",
    "cost_estimate": "$0.00004 per page"
  },
  "wiki-review-queue-digest": {
    "id": "wiki-review-queue-digest",
    "cron": "0 9 * * *",
    "description": "Daily digest of pending_review extraction count (v3.0 Tier B)",
    "skill": "wiki-review-queue-digest",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ],
    "fallback": "no_notification",
    "cost_estimate": "$0 per run (DB read + Telegram bot call)"
  }
};

export const SCHEDULE_IDS: readonly string[] = ["consistency-sweep-nightly","data-retention-scan","etl-product-dau-hourly","ingestion-source-poll","minion-queue-cleanup","morning-brief-assembly","stale-decision-check","wiki-embeddings-backfill","wiki-review-queue-digest"] as const;
