// AUTO-GENERATED by scripts/wave2-bundle-schedules.cjs from knowledge/schedules.yaml.
// Do not edit by hand. Re-run with: pnpm wave2:bundle-schedules
//
// Source version:  1.0.0
// Source timezone: Asia/Ho_Chi_Minh
// Schedule count:  16
// Generated at:    2026-05-30T05:50:38.525Z

import type { ScheduleEntry } from "./dispatcher.ts";

export const SCHEDULES: Record<string, ScheduleEntry> = {
  "morning-brief-assembly": {
    "id": "morning-brief-assembly",
    "cron": "45 5 * * *",
    "description": "Assemble morning brief 15 min before founder block",
    "skill": "synthesize-morning-brief",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ],
    "requires_api": "anthropic",
    "fallback": "queue_for_founder_review",
    "cost_estimate": "$0.03 per run"
  },
  "etl-product-dau-hourly": {
    "id": "etl-product-dau-hourly",
    "cron": "5 * * * *",
    "description": "Hourly ETL of Product DAU snapshot to metrics.product_dau_snapshot",
    "skill": "etl-product-dau-snapshot",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ],
    "requires_api": "supabase_product_read",
    "fallback": "queue_for_founder_review",
    "cost_estimate": "$0.00 per run"
  },
  "consistency-sweep-nightly": {
    "id": "consistency-sweep-nightly",
    "cron": "0 3 * * *",
    "description": "Nightly L3 sweep: insert pending consistency_checks rows for each L3 invariant",
    "skill": "consistency-sweep",
    "cost_estimate": "$0.00 per run"
  },
  "stale-decision-check": {
    "id": "stale-decision-check",
    "cron": "0 9 * * MON",
    "description": "Identify decisions needing review (Bài #15)",
    "skill": "stale-decision-detector",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ]
  },
  "data-retention-scan": {
    "id": "data-retention-scan",
    "cron": "0 3 * * *",
    "description": "GDPR data retention enforcement (Bài #16)",
    "skill": "data-retention-scanner"
  },
  "ingestion-source-poll": {
    "id": "ingestion-source-poll",
    "cron": "*/30 * * * *",
    "description": "Poll active ingestion sources (Bài #18)",
    "skill": "ingestion-source-poller",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ]
  },
  "minion-queue-cleanup": {
    "id": "minion-queue-cleanup",
    "cron": "0 4 * * *",
    "description": "Cleanup completed Minion jobs > 30 days (Bài #5)",
    "skill": "minion-queue-cleaner"
  },
  "wiki-embeddings-backfill": {
    "id": "wiki-embeddings-backfill",
    "cron": "0 * * * *",
    "description": "Backfill soft-deferred wiki embeddings (v2.0 G3 + v3.0 derived entities)",
    "skill": "wiki-embeddings-backfill",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ],
    "requires_api": "openai",
    "fallback": "skip_if_no_key",
    "cost_estimate": "$0.00004 per page"
  },
  "wiki-review-queue-digest": {
    "id": "wiki-review-queue-digest",
    "cron": "0 9 * * *",
    "description": "Daily digest of pending_review extraction count (v3.0 Tier B)",
    "skill": "wiki-review-queue-digest",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ],
    "fallback": "no_notification",
    "cost_estimate": "$0 per run (DB read + Telegram bot call)"
  },
  "docs-drift-nightly": {
    "id": "docs-drift-nightly",
    "cron": "30 2 * * *",
    "description": "Run /docs check to detect codebase ↔ MDX drift overnight",
    "skill": "docs-engine-check",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ],
    "fallback": "no_op",
    "cost_estimate": "$0 per run (deterministic; reads filesystem + writes ops.kpi_snapshots)"
  },
  "evolve-day30-calibration": {
    "id": "evolve-day30-calibration",
    "cron": "0 9 * * *",
    "description": "Run /evolve falsifiable efficacy gate; alert founder on PAUSE-RECOMMENDED",
    "skill": "eval-evo-calibrate-efficacy",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ],
    "fallback": "log_only",
    "cost_estimate": "$0 per run (deterministic; reads ops.agent_runs)"
  },
  "crm-to-gbrain-mirror": {
    "id": "crm-to-gbrain-mirror",
    "cron": "0 2 * * *",
    "description": "Nightly CRM → gbrain mirror (ETL public.companies billing fields → gbrain companies/ frontmatter)",
    "skill": "crm-to-gbrain-mirror",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ],
    "fallback": "queue_for_founder_review",
    "cost_estimate": "$0.05 per run"
  },
  "gbrain-consistency-nightly": {
    "id": "gbrain-consistency-nightly",
    "cron": "0 3 * * *",
    "description": "Nightly L1+L2+L3 gbrain invariant sweep → ops.consistency_checks",
    "skill": "gbrain-consistency-nightly",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ],
    "fallback": "log_only",
    "cost_estimate": "$0.02 per run"
  },
  "gbrain-dream-cycle": {
    "id": "gbrain-dream-cycle",
    "cron": "0 4 * * *",
    "description": "Nightly gbrain dream cycle (dedup + citation fix + contradiction detection + synthesis), run by gbrain-maintainer role",
    "skill": "gbrain-dream-cycle",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ],
    "fallback": "log_only",
    "cost_estimate": "$1.00 per run (~$30/mo cap)"
  },
  "resolver-v3-health-check": {
    "id": "resolver-v3-health-check",
    "cron": "0 * * * *",
    "description": "Canary mcp__supabase-ops__resolver_find call; alert founder on 3 consecutive failures",
    "skill": "resolver-v3-health-check",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ],
    "fallback": "log_only",
    "cost_estimate": "$0 per run (no LLM call; MCP read-only + audit insert)",
    "notes": "Stub handler — wired into supabase/functions/_shared/worker.ts in Sprint 4\nfollow-up PR. Active only post-CLAUDE.md-cutover Tier C ceremony.\n"
  },
  "skillopt-synth-prod-correlation-monthly": {
    "id": "skillopt-synth-prod-correlation-monthly",
    "cron": "0 9 1 * *",
    "description": "Monthly Spearman correlation between SkillOpt held-out scores and prod correction rates",
    "skill": "skillopt-synth-prod-correlation",
    "handler": "scripts/eval-evo/skillopt-synth-prod-correlation.cjs",
    "enabled_when_mode": [
      "hybrid",
      "full_api"
    ],
    "fallback": "log_only",
    "cost_estimate": "$0 per run (read-only SQL + pure-JS Spearman computation)",
    "notes": "Inserts to ops.kpi_snapshots(kpi_id='skillopt_synth_to_prod_correlation').\nEmits insufficient_data envelope (value=null) when <5 entities in 30-day\nwindow. Alert rules `skillopt-synth-to-prod-correlation` (critical < 0.3)\ninclude non-null guard so insufficient-data months don't trip critical.\nThe cron dispatcher reads `handler:` when `skill:` is absent — the\nhandler is a CJS script invoked directly. Wiring through the dispatcher\nis a Sprint 5 follow-up (first real /evolve skillopt run produces data\nto validate against).\n"
  }
};

export const SCHEDULE_IDS: readonly string[] = ["consistency-sweep-nightly","crm-to-gbrain-mirror","data-retention-scan","docs-drift-nightly","etl-product-dau-hourly","evolve-day30-calibration","gbrain-consistency-nightly","gbrain-dream-cycle","ingestion-source-poll","minion-queue-cleanup","morning-brief-assembly","resolver-v3-health-check","skillopt-synth-prod-correlation-monthly","stale-decision-check","wiki-embeddings-backfill","wiki-review-queue-digest"] as const;
