#!/usr/bin/env node
'use strict';
/**
 * scripts/video/scaffold.cjs — create a video project (capability video-platform)
 *
 * A project must be BORN ignore-correct. The founder's sync contract is:
 *   TEXT committed (SCRIPT.md, FOOTAGE.md, TIMELINE.*, YOUTUBE.md, index.html,
 *   run.json)  ·  MEDIA local (assets/, build/, out/)  ·  EXCEPT out/filmstrip.jpg,
 *   which is committed because it is the only auditable evidence a render was
 *   actually verified.
 *
 * That contract lives in video/.gitignore; this scaffolder just creates the shape
 * that fits it, and writes the asset folders with .gitkeep so the structure is
 * obvious to a teammate who clones and sees no media.
 *
 * Usage:
 *   node scripts/video/scaffold.cjs --slug=my-film [--type=explainer] [--style=ritsu]
 *                                   [--title="..."] [--force] [--json]
 *
 * Exit 0 = created, 1 = refused (exists without --force, unknown type), 2 = usage.
 */

const fs = require('fs');
const path = require('path');

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const PROJECTS_DIR = path.join(REPO_ROOT, 'video', 'projects');
const { UNIVERSAL_SLOTS, SLUG_RE } = require('./lib/params.cjs');
const state = require('./lib/state.cjs');

function loadTypes() {
  const yaml = require('js-yaml');
  const fp = path.join(REPO_ROOT, 'knowledge', 'video-types.yaml');
  const doc = yaml.load(fs.readFileSync(fp, 'utf-8')) || {};
  return Array.isArray(doc.types) ? doc.types : [];
}

function resolveType(types, id) {
  if (!id) return types.find((t) => t.default === true) || types[0];
  return types.find((t) => t.id === id || (Array.isArray(t.aliases) && t.aliases.includes(id))) || null;
}

function parseArgs(argv) {
  const o = { json: false, force: false };
  for (const a of argv) {
    if (a === '--json') o.json = true;
    else if (a === '--force') o.force = true;
    else if (a.startsWith('--slug=')) o.slug = a.slice(7);
    else if (a.startsWith('--type=')) o.type = a.slice(7);
    else if (a.startsWith('--style=')) o.style = a.slice(8);
    else if (a.startsWith('--title=')) o.title = a.slice(8);
  }
  return o;
}

const README = (slug, t, title) => `# ${title || slug}

**Type** \`${t.id}\` · **Style** \`${t.design_system}\` · **${t.resolution} @ ${t.fps}fps (${t.aspect})**
Target runtime ~${t.duration.target_s}s.

Built with \`/video\`. Regenerate or continue with:

\`\`\`bash
/video --resume --slug=${slug}
\`\`\`

## What is committed vs local

| Path | Committed? | Why |
|---|---|---|
| \`SCRIPT.md\` \`FOOTAGE.md\` \`TIMELINE.*\` \`YOUTUBE.md\` \`index.html\` \`run.json\` | ✅ | the actual IP — a teammate can read, review and edit the film |
| \`assets/\` \`build/\` \`out/\` | ❌ | heavy and reproducible |
| \`out/filmstrip.jpg\` | ✅ | the only evidence the render was verified |

Because media is local, \`--resume\` **re-probes the disk** rather than trusting
\`run.json\`. A fresh clone will correctly report every asset as missing.

## Asset codes

Files are named \`<CODE>-<NN>-b<BEAT>.<ext>\` — code, sequence, beat. Nothing else.
See \`FOOTAGE.md\` for the manifest (each row carries a sha256 so the committed
composition can be checked for coherence even without the bytes).
`;

const SCRIPT_STUB = (slug, t, title) => `# ${title || slug} — SHOOTING SCRIPT + PRODUCTION BIBLE

**Runtime** ~${t.duration.target_s}s · **Canvas** ${t.resolution} (${t.aspect}) · **fps** ${t.fps}
**Type** \`${t.id}\` · **Design system** \`../../design-systems/${t.design_system}/frame.md\`

> Generated by \`/video\` scaffold. Beats below are placeholders — run the script
> stage to brainstorm them, or pass \`--script=<ref>\` to transform an existing source.

---

## Beat map

| # | Beat | Time | Mode | Assets |
|---|---|---|---|---|
| 1 | _(tbd)_ | 0:00– | | |

---

## Beats

### BEAT 1 · _(tbd)_
- **[FRAME]**
- **[FOOTAGE]**
- **[ANIMATION]**
- **[TEXT MOTION]**
- **[ASSETS]**
- **[VO]**
- **[ON-SCREEN]**

---

## Tagged VO

_(per-beat narration with inline audio tags — this is what /voice synthesises)_

## Master asset checklist

_(filled by the assets stage; every on-screen numeric must cite an asset code)_
`;

const FOOTAGE_STUB = (t) => `# FOOTAGE — asset manifest

Every visual/audio asset has a **code**; the filename IS the code:

\`\`\`
<CODE>-<NN>-b<BEAT>.<ext>
\`\`\`

Whole-film assets use \`-all\`.

## Manifest

Each row is checksummed so CI can verify the committed composition is coherent
even though the media itself is gitignored.

| Code | Kind | Beat | File | sha256 | bytes | duration |
|---|---|---|---|---|---|---|
| _(none yet)_ | | | | | | |

## Slots for this type

${t.asset_slots.map((s) => `- \`${s}\`${(t.handoff || []).includes(s) ? '  **← human-supplied (hand-off)**' : ''}`).join('\n')}

## Hand-off

Slots marked hand-off cannot be generated: a human records them (screen capture)
or produces them externally (live action). \`/video\` emits exact specs and parks;
\`--resume\` picks up when the files land.
`;

function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.slug) { console.error('usage: scaffold.cjs --slug=<slug> [--type=<id>] [--style=<ds>] [--title=".."]'); process.exit(2); }
  if (!SLUG_RE.test(args.slug)) { console.error(`[FAIL] slug "${args.slug}" must match ${SLUG_RE}`); process.exit(1); }

  const types = loadTypes();
  const t = resolveType(types, args.type);
  if (!t) {
    console.error(`[FAIL] unknown type "${args.type}". Known: ${types.map((x) => x.id).join(', ')}`);
    process.exit(1);
  }
  if (t.status !== 'installed') {
    console.error(`[FAIL] type "${t.id}" is ${t.status} — it is registered but not built yet.`);
    process.exit(1);
  }

  const dir = path.join(PROJECTS_DIR, args.slug);
  if (fs.existsSync(dir) && !args.force) {
    console.error(`[FAIL] ${path.relative(REPO_ROOT, dir)} already exists (use --force to add missing pieces).`);
    process.exit(1);
  }

  const style = args.style || t.design_system;
  const created = [];
  const mk = (rel, content) => {
    const fp = path.join(dir, rel);
    fs.mkdirSync(path.dirname(fp), { recursive: true });
    if (!fs.existsSync(fp)) { fs.writeFileSync(fp, content, 'utf-8'); created.push(rel); }
  };

  // asset folders — only the slots this type declares, plus the derived dirs.
  for (const slot of t.asset_slots) {
    if (!UNIVERSAL_SLOTS.includes(slot)) continue;
    mk(path.join('assets', slot, '.gitkeep'), '');
  }
  mk(path.join('build', '.gitkeep'), '');
  mk(path.join('out', '.gitkeep'), '');

  // text artifacts
  mk('README.md', README(args.slug, t, args.title));
  if ((t.artifacts || []).includes('SCRIPT.md')) mk('SCRIPT.md', SCRIPT_STUB(args.slug, t, args.title));
  if ((t.artifacts || []).includes('FOOTAGE.md')) mk('FOOTAGE.md', FOOTAGE_STUB(t));

  // run.json — the state contract
  const s = state.create({ slug: args.slug, type: t.id, typeSpec: t, style });
  state.save(dir, s);
  created.push('run.json');

  const rel = path.relative(REPO_ROOT, dir);
  if (args.json) {
    console.log(JSON.stringify({ ok: true, dir: rel, type: t.id, style, created }, null, 2));
  } else {
    console.log(`created ${rel}`);
    for (const c of created.sort()) console.log(`   + ${c}`);
    console.log(`\ntype ${t.id} · style ${style} · ${t.resolution}@${t.fps} · target ~${t.duration.target_s}s`);
    console.log(`hand-off slots: ${(t.handoff || []).join(', ') || '(none)'}`);
  }
  process.exit(0);
}

if (require.main === module) main();
module.exports = { parseArgs, loadTypes, resolveType };
