import { defineDocs, defineConfig } from "fumadocs-mdx/config";

// Single doc collection covering all 9 source kinds.
// The MDX files under content/docs/ are generated by scripts/docs-sync.cjs
// from Tier 1 + .claude/ runtime sources. Each MDX has frontmatter:
//   - title: string
//   - description: string
//   - source_path: string (relative to repo root; the canonical source)
//   - source_hash: string (sha256 of canonicalized source content)
//   - generated_at: ISO8601 timestamp
//   - generated_by: "docs-engine v0.1.0" (the idempotency marker — CTO mod #1)
//   - category: "skill" | "agent" | "hook" | "command" | "charter" | "governance" | "pillar" | "sop" | "tier1-yaml" | "tutorial"
//
// Hand-written tutorials additionally carry:
//   - tutorial_last_verified_at: ISO8601 timestamp (CPO mod #1; monthly verification)

export const { docs, meta } = defineDocs({
  dir: "content/docs",
});

export default defineConfig({
  mdxOptions: {
    // Add remark/rehype plugins here as needs evolve. v1.0 ships defaults.
  },
});
